###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Marta Wayne",
    "age": "49",
    "email": "fancywayne@gmail.com"
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/63c02394614543e9ff6994e4 HTTP/1.1

###
PUT http://localhost:9000/api/users/63c02394614543e9ff6994e4 HTTP/1.1
Content-Type: application/json

{
    "name": "Bruce Wayne",
    "age": 52,
    "email": "newbatman@gmail.com"
}

###
DELETE http://localhost:9000/api/users/63c0231df642b289adf55726 HTTP/1.1